rest:
    type: rest
    resource: RestBundle\Controller\IngredientController
    prefix:   /api/

ingredient:
    resource: "@IngredientBundle/Controller"
    type:   annotation

import:
    resource: "@ImportBundle/Controller"
    type:   annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
