rest:
    type: rest
    resource: RestBundle\Controller\IngredientController
    prefix:   /

ingredient:
    resource: "@IngredientBundle/Resources/config/routing.xml"
    prefix:   /

import:
    resource: "@ImportBundle/Resources/config/routing.xml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
